language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
    - extra-android-m2repository
#    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17

before_install:
  - chmod +x gradlew